version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:2.3.1
    container_name: tomcat8_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  tomcat8:
    image: test-tomcat8
    container_name: tomcat8
    ports:
      - '80:8080'
    env_file:
      - .env
